# Custom firewall rules
# Put your custom firewall rules in for your Kiosk here, layout is below
# default['firewallrule']['itemname']['name'] = 'Rule Name'
# default['firewallrule']['itemname']['ruleaction'] = 'Allow'
# default['firewallrule']['itemname']['description'] = 'Rule Description'
# default['firewallrule']['itemname']['direction'] = 'Inbound'
# default['firewallrule']['itemname']['enabled'] = 'True'
# default['firewallrule']['itemname']['group'] = 'Custom rule by Chef'
# default['firewallrule']['itemname']['interfacetype'] = 'Any'
# default['firewallrule']['itemname']['localaddress'] = ''
# default['firewallrule']['itemname']['localport'] = 'Any'
# default['firewallrule']['itemname']['profile'] = 'Any'
# default['firewallrule']['itemname']['program'] = 'System'
# default['firewallrule']['itemname']['protocol'] = 'ICMPv4'
# default['firewallrule']['itemname']['remoteaddress'] = 'Any'
# default['firewallrule']['itemname']['remoteport'] = 'Any'
# default['firewallrule']['itemname']['service'] = ''

# Placeholder rule
default['firewallrule']['placeholder']['name'] = 'Placeholder Rule'
default['firewallrule']['placeholder']['ruleaction'] = 'Allow'
default['firewallrule']['placeholder']['description'] = 'Placeholder Rule'
default['firewallrule']['placeholder']['direction'] = 'Inbound'
default['firewallrule']['placeholder']['enabled'] = 'True'
default['firewallrule']['placeholder']['group'] = 'Custom rule by Chef'
default['firewallrule']['placeholder']['interfacetype'] = 'Any'
default['firewallrule']['placeholder']['localaddress'] = ''
default['firewallrule']['placeholder']['localport'] = 'Any'
default['firewallrule']['placeholder']['profile'] = 'Any'
default['firewallrule']['placeholder']['program'] = 'System'
default['firewallrule']['placeholder']['protocol'] = '443'
default['firewallrule']['placeholder']['remoteaddress'] = 'Any'
default['firewallrule']['placeholder']['remoteport'] = 'Any'
default['firewallrule']['placeholder']['service'] = ''
